export const STOCK_UNIVERSE: Record<string, string[]> = {
  Technology: [
    'AAPL','MSFT','NVDA','GOOGL','GOOG','META','AVGO','AMD','CRM','ORCL',
    'QCOM','TXN','NOW','ADBE','AMAT','CSCO','IBM','INTU','MU','KLAC',
    'LRCX','MRVL','PLTR','SNOW','PANW','CRWD','DDOG','NET','FTNT','ZS',
    'PYPL','ACN','DELL','HPQ','UBER','COIN','HOOD','SHOP','SQ','TTD',
    'ANET','NXPI','MCHP','ON','STX','WDC','NTAP','KEYS','TER','ANSS',
    'CDNS','SNPS','LDOS','EPAM','OKTA','TWLO','DOCU','VEEV','HUBS',
    'ZM','TEAM','ATLASSIAN','WDAY','SPLK','MDB','COUP','BILL','SMAR',
    'U','RBLX','APP','APPLOVIN','GTLB','DXCM','FICO','FSLR','ENPH',
    'GEN','AKAM','CDW','JNPR','FFIV','VRSN','WEX','PAYC','PCTY',
    'NICE','CTSH','WIT','INFY','TCS','HCL','WIPRO','GLOB','EPAM',
    'SWKS','MPWR','ENTG','ONTO','WOLF','OLED','RMBS','SLAB','ALGM',
    'SMAR','TOST','FRSH','AI','PATH','BBAI','SOUN','IREN','CORZ',
    'MSTR','CLSK','RIOT','MARA','CIFR','HUT','BTBT',
  ],
  'Communication Services': [
    'NFLX','DIS','T','VZ','CMCSA','SPOT','ROKU','WBD',
    'SNAP','PINS','EA','TTWO','PARA','MTCH','LYV',
    'TMUS','CHTR','FOXA','FOX','NWSA','NWS','IPG','OMC',
    'ZETA','IAS','MGNI','PUBM','TTD','APPS','GENI','DV',
    'LUMN','ATUS','CABO','WOW','SHEN','CNSL',
  ],
  'Consumer Discretionary': [
    'AMZN','TSLA','HD','MCD','NKE','SBUX','LOW','TGT','BKNG','GM','F',
    'ABNB','DASH','EXPE','ETSY','EBAY','CMG','YUM','DPZ','MAR','HLT',
    'RIVN','LCID','MGM','LVS','RH','BBY','TJX','ROSS','DLTR','DG',
    'HAS','MAT','POOL','ORLY','AZO','AAP','GPC','KMX','LAD','AN',
    'DKNG','PENN','CZR','WYNN','NCLH','CCL','RCL','H','IHG','CHH',
    'LULU','GPS','PVH','RL','TPR','VFC','OXM','G',
    'PTON','SFIX','CHWY','W','OSTK','PRTS','OLPX',
    'MHK','WHR','SWK','WSO','AOS','ALLE','LII','WMS',
    'MTD','SCI','HBI','GOOS','ODP','GME','AMC',
  ],
  'Consumer Staples': [
    'PG','KO','PEP','WMT','COST','CL','MO','PM','KHC','GIS',
    'MDLZ','SYY','HSY','CHD','CAG','STZ','TAP','EL','COTY',
    'KR','SFM','GO','CASY','WEIS','VRGN','USFD','PFGC',
    'BG','ADM','INGR','CALM','TSN','HRL','LW','LANC',
    'CLX','SPB','ENER','HPC','JAH',
  ],
  Healthcare: [
    'UNH','JNJ','LLY','ABBV','MRK','TMO','ABT','PFE','AMGN','BMY',
    'CVS','GILD','REGN','VRTX','ISRG','MDT','SYK','CI','ELV','MRNA',
    'BSX','HCA','HUM','DXCM','DHR','IQV','ZBH','BIIB','HOLX','BAX',
    'BDX','EW','IDXX','MTD','RMD','ALGN','NVST','TECH','STE','ICU',
    'IONS','ALNY','BMRN','EXEL','HALO','SRPT','ARWR','MDGL',
    'ACAD','SAGE','PTGX','RCKT','RXRX','VERV','BEAM','NTLA',
    'CNC','MOH','WCG','MCK','CAH','ABC','PDCO','HSIC',
    'VTRS','PRGO','JAZZ','ENDP','EGRX','SUPN','PAHC',
  ],
  Financials: [
    'JPM','BAC','WFC','GS','MS','V','MA','AXP','BLK','C',
    'SCHW','USB','COF','PNC','TFC','MMC','CB','MET','PRU','AFL',
    'SPGI','MCO','ICE','CME','BK','STT','FITB','RF','KEY','HBAN',
    'CFG','MTB','ZION','CBSH','UMPQ','FHN','SNV','BOK','BOKF',
    'ALLY','SYF','DFS','CACC','OMF','NAVI','SLM','SOFI',
    'HOOD','LPLA','RJF','SF','MKTX','CBOE','NDAQ','OWL',
    'PFG','LNC','VOYA','GL','FG','RGA','AIZ','EQH',
    'WTW','AON','AJG','TW','ERIE','HIG','CNA','TRV',
    'ACGL','RNR','GLNG','MKL','Y','BRK.B','BRK.A',
    'FDS','BR','SEIC','NTRS','IVZ','AMG','BEN','TROW',
    'TREE','RDFN','OPEN','UWMC','RKT','GHLD','VRM','LOB',
  ],
  Energy: [
    'XOM','CVX','COP','MPC','VLO','PSX','EOG','PXD','OXY','SLB',
    'HAL','BKR','FANG','DVN','HES','MRO','APA','CTRA','MTDR',
    'SM','CPE','CIVI','PDCE','REX','VTLE','NOG','BATL',
    'KMI','WMB','OKE','EPD','ET','MPLX','PAA','AM','TRGP',
    'LNG','CQP','NFE','GLNG','GLOG','TTE',
    'BP','SHEL','E','SU','CVE','IMO',
  ],
  Materials: [
    'LIN','APD','SHW','ECL','PPG','IFF','NEM','FCX','NUE','STLD',
    'RS','CMC','CLF','AA','CENX','MP','USLM','MLM','VMC','EXP',
    'CF','MOS','FMC','ICL','MEOH','OLN','EMN','CC','HUN',
    'PKG','IP','WRK','SEE','SON','SLGN','BERY','PTVE',
    'BCC','LPX','WY','RYN','PCH','PH',
  ],
  Industrials: [
    'GE','CAT','HON','BA','LMT','RTX','GD','NOC','L3H','HII',
    'ITW','EMR','ETN','PH','ROK','AME','ODFL','UNP','CSX','NSC',
    'XPO','JBHT','CHRW','EXPD','GXO','SAIA','AXL','FDX','UPS',
    'DE','AGCO','CNHI','PCAR','WCN','RSG','WM','SRCL',
    'FAST','GWW','AIT','MSM','CNXC','EXPO',
    'CARR','OTIS','TT','JCI','LII','WMS','TREX','FBHS',
    'CMI','ALSN','TRN','GBX','WAB','GNRC','HUBB','ACA',
    'ROP','CPRT','VRSK','TDY','TXT','HWM','SPX','MIDD',
    'REVG','WKHS','RIDE','GOEV','HYLN','SEE',
  ],
  'Real Estate': [
    'AMT','PLD','CCI','EQIX','PSA','O','SPG','VICI','WELL','DLR',
    'AVB','EQR','ESS','MAA','UDR','CPT','NNN','BXP','VNO','KIM',
    'REG','FRT','ROIC','WSR','SITC','RPAI','PECO','CTO',
    'EXR','CUBE','LSI','NSA','PSB','REXR','FR','EGP','STAG',
    'IIPR','SAFE','LADR','ABR','RITM','ACRE','RC','NLY','LOAN',
    'IRM','SBAC','UNIT','LUMN','CONE','QTS','INDT',
    'WPC','EPR','SRC','NTST','ADC','FCPT','PINE',
    'PEAK','VTR','OHI','MPW','SBRA','CTRE','CSR',
    'AIV','AIRC','NSA','NHI','NXRT','NRE','BRT','CLPR',
    'LAND','FPI','AFCG','AHH','ALEX','GMRE','NXNX',
  ],
  Utilities: [
    'NEE','DUK','SO','D','AEP','EXC','SRE','PCG','PEG','ED',
    'WEC','ES','AWK','ETR','EIX','AES','CMS','NI','LNT','EVRG',
    'PPL','OGE','PNW','NWE','AVA','POR','HE','MGEE','UIL',
    'AGR','AQN','BIP','BEPC','CWEN','NEP','PEGI','TERP',
    'IDA','OTTR','AEE','CNP','OGS','NWN','SR',
  ],
  ETFs: [
    'SPY','QQQ','IWM','DIA','VTI','VOO','VEA','VWO','EEM','EFA',
    'AGG','BND','LQD','HYG','TLT','SHY','IEF','GLD','SLV','IAU',
    'USO','UNG','DBA','PDBC','CORN','WEAT','SOYB',
    'XLK','XLF','XLE','XLV','XLI','XLP','XLY','XLU','XLB','XLRE',
    'VGT','VFH','VDE','VHT','VIS','VPU','VAW','VCR','VDC','VOX',
    'SOXX','SMH','HACK','CIBR','BUG','ARKK','ARKG','ARKW','ARKF','ARKX',
    'TQQQ','SQQQ','SPXL','SPXS','UPRO','SOXL','SOXS','LABD','LABU',
    'SCHD','JEPI','JEPQ','DIVO','HDV','VYM','DVY','SDY','SPYD',
    'VNQ','SCHH','IYR','MORT','REM','SRET','KBWY',
    'IBIT','FBTC','EZBC','BTCO','BRRR','HODL',
    'IEMG','VGK','VXUS','ACWI','URTH','IOO',
    'RSP','QQEW','XMMO','IJR','IWO','IWN','MDY',
    'FTEC','FDN','SKYY','CLOU','IGV','WCLD',
    'MOO','XME','GDX','GDXJ','SIL','SILJ','PICK',
    'IBB','XBI','BBH','ARKG','GNOM','IDNA',
    'IYT','XTN','JETS','AWAY','FLY',
    'EWJ','EWZ','EWC','EWA','EWG','EWU','EWI','EWQ',
    'FXI','KWEB','CQQQ','MCHI','ASHR','GXC',
    'TAN','ICLN','QCLN','ACES','SMOG','GRID',
    'BITO','ETHW','BITU','ETHE','GBTC',
    'PFF','PSK','PFFD','FPE','PFXF',
    'VMBS','MBB','GNMA','CMBS',
    'TIP','SCHP','VTIP','STPZ','FIPDX',
    'SHV','SGOV','USFR','TFLO','BIL',
  ],
  REITs: [
    'PLD','AMT','EQIX','CCI','PSA','O','VICI','SPG','DLR','WELL',
    'AVB','EQR','ESS','MAA','UDR','NNN','BXP','VNO','ARE','CBRE',
    'EXR','CUBE','NSA','LSI','REXR','FR','EGP','STAG','DRE','TRNO',
    'WPC','EPR','SRC','ADC','NHI','OHI','MPW','VTR','PEAK','SBRA',
    'IRM','SBAC','CONE','AMH','INVH','TMHC','AIV','AIRC','CSR',
    'BRT','CLPR','NRE','NXRT','GMRE','SAFE','LADR',
  ],
  International: [
    'NU','PBR','VALE','ITUB','BBD','ABEV','BSBR','ERJ','XP','STNE',
    'PAGS','VIV','GGB','SBS','CIG','MELI','TSM','SE','ASML','NVO',
    'TM','SONY','SAP','RIO','BHP','UL','TD','RY',
  ],
}

export const STOCK_NAMES: Record<string, string> = {
  // International / ADRs
  NU:'Nu Holdings',PBR:'Petrobras',VALE:'Vale S.A.',ITUB:'Itaú Unibanco',
  BBD:'Banco Bradesco',ABEV:'Ambev S.A.',BSBR:'Banco Santander Brasil',
  ERJ:'Embraer',XP:'XP Inc.',STNE:'StoneCo',PAGS:'PagSeguro',
  VIV:'Telefônica Brasil',GGB:'Gerdau',SBS:'Sabesp',CIG:'Cemig',
  MELI:'MercadoLibre',TSM:'Taiwan Semiconductor',SE:'Sea Ltd',
  ASML:'ASML Holding',NVO:'Novo Nordisk',TM:'Toyota Motor',
  SONY:'Sony Group',SAP:'SAP SE',RIO:'Rio Tinto',BHP:'BHP Group',
  UL:'Unilever',TD:'Toronto-Dominion Bank',RY:'Royal Bank of Canada',
  // Real Estate (mortgage REITs)
  NLY:'Annaly Capital Management', LOAN:'Manhattan Bridge Capital',
  // Technology
  AAPL:'Apple Inc.',MSFT:'Microsoft Corp.',NVDA:'NVIDIA Corp.',
  GOOGL:'Alphabet Inc. (A)',GOOG:'Alphabet Inc. (C)',META:'Meta Platforms',
  AVGO:'Broadcom Inc.',AMD:'Advanced Micro Devices',CRM:'Salesforce',
  ORCL:'Oracle Corp.',QCOM:'Qualcomm',TXN:'Texas Instruments',
  NOW:'ServiceNow',ADBE:'Adobe Inc.',AMAT:'Applied Materials',
  CSCO:'Cisco Systems',IBM:'IBM Corp.',INTU:'Intuit Inc.',
  MU:'Micron Technology',KLAC:'KLA Corp.',LRCX:'Lam Research',
  MRVL:'Marvell Technology',PLTR:'Palantir Technologies',
  SNOW:'Snowflake',PANW:'Palo Alto Networks',CRWD:'CrowdStrike',
  DDOG:'Datadog',NET:'Cloudflare',FTNT:'Fortinet',ZS:'Zscaler',
  PYPL:'PayPal Holdings',ACN:'Accenture',DELL:'Dell Technologies',
  HPQ:'HP Inc.',UBER:'Uber Technologies',COIN:'Coinbase Global',
  HOOD:'Robinhood Markets',SHOP:'Shopify',SQ:'Block Inc.',
  TTD:'The Trade Desk',ANET:'Arista Networks',NXPI:'NXP Semiconductors',
  MCHP:'Microchip Technology',ON:'ON Semiconductor',STX:'Seagate Technology',
  WDC:'Western Digital',NTAP:'NetApp',KEYS:'Keysight Technologies',
  TER:'Teradyne',ANSS:'Ansys',CDNS:'Cadence Design',SNPS:'Synopsys',
  EPAM:'EPAM Systems',OKTA:'Okta Inc.',TWLO:'Twilio',DOCU:'DocuSign',
  VEEV:'Veeva Systems',HUBS:'HubSpot',ZM:'Zoom Video',WDAY:'Workday',
  MDB:'MongoDB',FICO:'Fair Isaac Corp.',FSLR:'First Solar',ENPH:'Enphase Energy',
  GEN:'Gen Digital',AKAM:'Akamai Technologies',CDW:'CDW Corp.',
  CTSH:'Cognizant Technology',SWKS:'Skyworks Solutions',MPWR:'Monolithic Power',
  ENTG:'Entegris',MSTR:'MicroStrategy',PATH:'UiPath',APP:'Applovin',
  AI:'C3.ai',TOST:'Toast Inc.',FRSH:'Freshworks',GTLB:'GitLab',
  CLSK:'CleanSpark',RIOT:'Riot Platforms',MARA:'Marathon Digital',
  CIFR:'Cipher Mining',HUT:'Hut 8 Corp.',BTBT:'Bit Digital',
  SOUN:'SoundHound AI',IREN:'Iris Energy',CORZ:'Core Scientific',
  // Communication Services
  NFLX:'Netflix',DIS:'Walt Disney Co.',T:'AT&T',VZ:'Verizon',
  CMCSA:'Comcast',SPOT:'Spotify',ROKU:'Roku Inc.',WBD:'Warner Bros. Discovery',
  SNAP:'Snap Inc.',PINS:'Pinterest',EA:'Electronic Arts',
  TTWO:'Take-Two Interactive',PARA:'Paramount Global',MTCH:'Match Group',
  LYV:'Live Nation Entertainment',TMUS:'T-Mobile US',CHTR:'Charter Communications',
  FOXA:'Fox Corp. (A)',FOX:'Fox Corp. (B)',NWSA:'News Corp (A)',NWS:'News Corp (B)',
  IPG:'Interpublic Group',OMC:'Omnicom Group',ZETA:'Zeta Global',GENI:'Genius Sports',
  LUMN:'Lumen Technologies',ATUS:'Altice USA',CABO:'Cable One',
  // Consumer Discretionary
  AMZN:'Amazon.com',TSLA:'Tesla Inc.',HD:'Home Depot',MCD:"McDonald's",
  NKE:'Nike Inc.',SBUX:'Starbucks',LOW:"Lowe's",TGT:'Target Corp.',
  BKNG:'Booking Holdings',GM:'General Motors',F:'Ford Motor',
  ABNB:'Airbnb',DASH:'DoorDash',EXPE:'Expedia Group',
  ETSY:'Etsy Inc.',EBAY:'eBay Inc.',CMG:'Chipotle Mexican Grill',
  YUM:'Yum! Brands',DPZ:"Domino's Pizza",MAR:'Marriott International',
  HLT:'Hilton Worldwide',RIVN:'Rivian Automotive',LCID:'Lucid Group',
  MGM:'MGM Resorts',LVS:'Las Vegas Sands',RH:'RH (Restoration Hardware)',
  BBY:'Best Buy',TJX:'TJX Companies',ROSS:'Ross Stores',
  DLTR:'Dollar Tree',DG:'Dollar General',HAS:'Hasbro',MAT:'Mattel',
  ORLY:"O'Reilly Automotive",AZO:'AutoZone',AAP:'Advance Auto Parts',
  KMX:'CarMax',LAD:'Lithia Motors',AN:'AutoNation',DKNG:'DraftKings',
  PENN:'Penn Entertainment',CZR:"Caesars Entertainment",WYNN:'Wynn Resorts',
  NCLH:'Norwegian Cruise Line',CCL:'Carnival Corp.',RCL:'Royal Caribbean',
  LULU:'Lululemon Athletica',GPS:'Gap Inc.',PVH:'PVH Corp.',RL:'Ralph Lauren',
  TPR:'Tapestry',VFC:'VF Corp.',PTON:'Peloton Interactive',
  SFIX:'Stitch Fix',CHWY:'Chewy Inc.',W:'Wayfair',GME:'GameStop',AMC:'AMC Entertainment',
  // Consumer Staples
  PG:'Procter & Gamble',KO:'Coca-Cola',PEP:'PepsiCo',WMT:'Walmart',
  COST:'Costco Wholesale',CL:'Colgate-Palmolive',MO:'Altria Group',
  PM:'Philip Morris',KHC:'Kraft Heinz',GIS:'General Mills',
  MDLZ:'Mondelez International',SYY:'Sysco Corp.',HSY:'Hershey Co.',
  CHD:'Church & Dwight',CAG:'Conagra Brands',STZ:'Constellation Brands',
  TAP:'Molson Coors',EL:'Estee Lauder',KR:'Kroger',SFM:"Sprouts Farmers Market",
  TSN:"Tyson Foods",HRL:'Hormel Foods',LW:"Lamb Weston",
  CLX:'Clorox Co.',BG:'Bunge Global',ADM:'Archer-Daniels-Midland',
  // Healthcare
  UNH:'UnitedHealth Group',JNJ:'Johnson & Johnson',LLY:'Eli Lilly',
  ABBV:'AbbVie',MRK:'Merck & Co.',TMO:'Thermo Fisher Scientific',
  ABT:'Abbott Laboratories',PFE:'Pfizer',AMGN:'Amgen',BMY:'Bristol-Myers Squibb',
  CVS:'CVS Health',GILD:'Gilead Sciences',REGN:'Regeneron Pharmaceuticals',
  VRTX:'Vertex Pharmaceuticals',ISRG:'Intuitive Surgical',MDT:'Medtronic',
  SYK:'Stryker Corp.',CI:'Cigna Group',ELV:'Elevance Health',MRNA:'Moderna',
  BSX:'Boston Scientific',HCA:'HCA Healthcare',HUM:'Humana',DXCM:'DexCom',
  DHR:'Danaher',IQV:'IQVIA Holdings',ZBH:'Zimmer Biomet',BIIB:'Biogen',
  HOLX:'Hologic',BAX:'Baxter International',BDX:'Becton Dickinson',
  EW:'Edwards Lifesciences',IDXX:'IDEXX Laboratories',RMD:'ResMed',
  ALGN:'Align Technology',MCK:'McKesson',CAH:'Cardinal Health',
  ABC:'AmerisourceBergen',CNC:'Centene Corp.',MOH:'Molina Healthcare',
  // Financials
  JPM:'JPMorgan Chase',BAC:'Bank of America',WFC:'Wells Fargo',
  GS:'Goldman Sachs',MS:'Morgan Stanley',V:'Visa Inc.',MA:'Mastercard',
  AXP:'American Express',BLK:'BlackRock',C:'Citigroup',
  SCHW:'Charles Schwab',USB:'U.S. Bancorp',COF:'Capital One',
  PNC:'PNC Financial',TFC:'Truist Financial',MMC:'Marsh McLennan',
  CB:'Chubb Ltd.',MET:'MetLife',PRU:'Prudential Financial',AFL:'Aflac',
  SPGI:'S&P Global',MCO:"Moody's Corp.",ICE:'Intercontinental Exchange',
  CME:'CME Group',BK:'Bank of New York Mellon',STT:'State Street',
  FITB:'Fifth Third Bancorp',RF:'Regions Financial',KEY:'KeyCorp',
  HBAN:'Huntington Bancshares',CFG:'Citizens Financial',MTB:'M&T Bank',
  ALLY:'Ally Financial',SYF:'Synchrony Financial',DFS:'Discover Financial',
  SOFI:'SoFi Technologies',NDAQ:'Nasdaq Inc.',CBOE:'Cboe Global Markets',
  TROW:'T. Rowe Price',BEN:'Franklin Templeton',IVZ:'Invesco',AMG:'Affiliated Managers',
  PFG:'Principal Financial',LNC:'Lincoln National',VOYA:'Voya Financial',
  RGA:'Reinsurance Group',AIZ:'Assurant',EQH:'Equitable Holdings',
  WTW:'Willis Towers Watson',AON:'Aon plc',AJG:'Arthur J. Gallagher',
  HIG:'Hartford Financial',CNA:'CNA Financial',TRV:'Travelers Companies',
  ACGL:'Arch Capital Group','BRK.B':'Berkshire Hathaway (B)','BRK.A':'Berkshire Hathaway (A)',
  FDS:'FactSet Research',BR:'Broadridge Financial',SEIC:'SEI Investments',
  NTRS:'Northern Trust',TREE:'LendingTree',LPLA:'LPL Financial',
  RJF:'Raymond James Financial',SF:'Stifel Financial',
  // Energy
  XOM:'Exxon Mobil',CVX:'Chevron Corp.',COP:'ConocoPhillips',
  MPC:'Marathon Petroleum',VLO:'Valero Energy',PSX:'Phillips 66',
  EOG:'EOG Resources',PXD:'Pioneer Natural Resources',OXY:'Occidental Petroleum',
  SLB:'SLB (Schlumberger)',HAL:'Halliburton',BKR:'Baker Hughes',
  FANG:'Diamondback Energy',DVN:'Devon Energy',HES:'Hess Corp.',
  MRO:'Marathon Oil',APA:'APA Corp.',CTRA:'Coterra Energy',MTDR:'Matador Resources',
  SM:'SM Energy',KMI:'Kinder Morgan',WMB:'Williams Companies',
  OKE:'ONEOK',EPD:'Enterprise Products Partners',ET:'Energy Transfer',
  MPLX:'MPLX LP',PAA:'Plains All American',TRGP:'Targa Resources',
  LNG:'Cheniere Energy',CQP:'Cheniere Energy Partners',NFE:'New Fortress Energy',
  // Materials
  LIN:'Linde plc',APD:'Air Products',SHW:'Sherwin-Williams',ECL:'Ecolab',
  PPG:'PPG Industries',IFF:'International Flavors',NEM:'Newmont Corp.',
  FCX:'Freeport-McMoRan',NUE:'Nucor Corp.',STLD:'Steel Dynamics',
  RS:'Reliance Steel',CMC:'Commercial Metals',CLF:'Cleveland-Cliffs',
  AA:'Alcoa Corp.',MLM:'Martin Marietta Materials',VMC:'Vulcan Materials',
  CF:'CF Industries',MOS:'Mosaic Co.',FMC:'FMC Corp.',
  PKG:'Packaging Corp.',IP:'International Paper',WRK:'WestRock',
  // Industrials
  GE:'GE Aerospace',CAT:'Caterpillar',HON:'Honeywell',BA:'Boeing',
  LMT:'Lockheed Martin',RTX:'RTX Corp.',GD:'General Dynamics',
  NOC:'Northrop Grumman',ITW:'Illinois Tool Works',EMR:'Emerson Electric',
  ETN:'Eaton Corp.',PH:'Parker Hannifin',ROK:'Rockwell Automation',
  AME:'AMETEK',ODFL:'Old Dominion Freight',UNP:'Union Pacific',
  CSX:'CSX Corp.',NSC:'Norfolk Southern',XPO:'XPO Inc.',
  JBHT:'J.B. Hunt Transport',CHRW:'C.H. Robinson',EXPD:'Expeditors International',
  GXO:'GXO Logistics',SAIA:'Saia Inc.',FDX:'FedEx',UPS:'United Parcel Service',
  DE:'Deere & Co.',AGCO:'AGCO Corp.',PCAR:'PACCAR',WCN:'Waste Connections',
  RSG:'Republic Services',WM:'Waste Management',FAST:'Fastenal',
  GWW:'W.W. Grainger',CARR:'Carrier Global',OTIS:'Otis Worldwide',
  TT:'Trane Technologies',JCI:'Johnson Controls',LII:'Lennox International',
  CMI:'Cummins',GNRC:'Generac Holdings',ROP:'Roper Technologies',
  CPRT:'Copart',VRSK:'Verisk Analytics',TDY:'Teledyne Technologies',
  TXT:'Textron',HWM:'Howmet Aerospace',SPX:'SPX Technologies',
  REVG:'REV Group',
  // Real Estate / REITs
  AMT:'American Tower',PLD:'Prologis',CCI:'Crown Castle',EQIX:'Equinix',
  PSA:'Public Storage',O:'Realty Income',SPG:'Simon Property Group',
  VICI:'VICI Properties',WELL:'Welltower',DLR:'Digital Realty Trust',
  AVB:'AvalonBay Communities',EQR:'Equity Residential',ESS:'Essex Property Trust',
  MAA:'Mid-America Apartment',UDR:'UDR Inc.',NNN:'NNN REIT',
  BXP:'Boston Properties',VNO:'Vornado Realty',ARE:'Alexandria Real Estate',
  CBRE:'CBRE Group',EXR:'Extra Space Storage',CUBE:'CubeSmart',
  NSA:'National Storage Affiliates',LSI:'Life Storage',REXR:'Rexford Industrial',
  FR:'First Industrial Realty',EGP:'EastGroup Properties',STAG:'STAG Industrial',
  WPC:'W. P. Carey',EPR:'EPR Properties',SRC:'Spirit Realty',ADC:'Agree Realty',
  NHI:'National Health Investors',OHI:'Omega Healthcare',MPW:'Medical Properties Trust',
  VTR:'Ventas',PEAK:'Healthpeak Properties',SBRA:'Sabra Health Care',
  IRM:'Iron Mountain',SBAC:'SBA Communications',AMH:'American Homes 4 Rent',
  INVH:'Invitation Homes',SAFE:'Safehold',LADR:'Ladder Capital',
  IIPR:'Innovative Industrial Properties',LAND:'Gladstone Land',FPI:'Farmland Partners',
  // Utilities
  NEE:'NextEra Energy',DUK:'Duke Energy',SO:'Southern Co.',D:'Dominion Energy',
  AEP:'American Electric Power',EXC:'Exelon',SRE:'Sempra Energy',
  PCG:'PG&E Corp.',PEG:'Public Service Enterprise',ED:'Consolidated Edison',
  WEC:'WEC Energy Group',ES:'Eversource Energy',AWK:'American Water Works',
  ETR:'Entergy Corp.',EIX:'Edison International',AES:'AES Corp.',
  CMS:'CMS Energy',NI:'NiSource',LNT:'Alliant Energy',EVRG:'Evergy',
  PPL:'PPL Corp.',OGE:'OGE Energy',PNW:'Pinnacle West Capital',
  AGR:'Avangrid',AQN:'Algonquin Power',BIP:'Brookfield Infrastructure',
  CWEN:'Clearway Energy',NEP:'NextEra Energy Partners',
  IDA:'IDACORP',AEE:'Ameren Corp.',CNP:'CenterPoint Energy',
  // ETFs
  SPY:'SPDR S&P 500 ETF',QQQ:'Invesco QQQ Trust',IWM:'iShares Russell 2000 ETF',
  DIA:'SPDR Dow Jones ETF',VTI:'Vanguard Total Stock Market ETF',
  VOO:'Vanguard S&P 500 ETF',VEA:'Vanguard FTSE Developed Markets ETF',
  VWO:'Vanguard FTSE Emerging Markets ETF',EEM:'iShares MSCI Emerging Markets ETF',
  EFA:'iShares MSCI EAFE ETF',AGG:'iShares Core US Aggregate Bond ETF',
  BND:'Vanguard Total Bond Market ETF',LQD:'iShares iBoxx Investment Grade ETF',
  HYG:'iShares High Yield Corporate Bond ETF',TLT:'iShares 20+ Year Treasury ETF',
  SHY:'iShares 1-3 Year Treasury ETF',IEF:'iShares 7-10 Year Treasury ETF',
  GLD:'SPDR Gold Shares',SLV:'iShares Silver Trust',IAU:'iShares Gold Trust',
  USO:'United States Oil Fund',UNG:'United States Natural Gas Fund',
  XLK:'Technology Select Sector SPDR',XLF:'Financial Select Sector SPDR',
  XLE:'Energy Select Sector SPDR',XLV:'Health Care Select Sector SPDR',
  XLI:'Industrial Select Sector SPDR',XLP:'Consumer Staples Select Sector SPDR',
  XLY:'Consumer Discretionary Select Sector SPDR',XLU:'Utilities Select Sector SPDR',
  XLB:'Materials Select Sector SPDR',XLRE:'Real Estate Select Sector SPDR',
  VGT:'Vanguard Information Technology ETF',VFH:'Vanguard Financials ETF',
  VDE:'Vanguard Energy ETF',VHT:'Vanguard Health Care ETF',
  VIS:'Vanguard Industrials ETF',VPU:'Vanguard Utilities ETF',
  VAW:'Vanguard Materials ETF',VCR:'Vanguard Consumer Discretionary ETF',
  VDC:'Vanguard Consumer Staples ETF',VOX:'Vanguard Communication Services ETF',
  SOXX:'iShares Semiconductor ETF',SMH:'VanEck Semiconductor ETF',
  HACK:'ETFMG Prime Cyber Security ETF',CIBR:'First Trust NASDAQ Cybersecurity ETF',
  ARKK:'ARK Innovation ETF',ARKG:'ARK Genomic Revolution ETF',
  ARKW:'ARK Next Generation Internet ETF',ARKF:'ARK Fintech Innovation ETF',
  ARKX:'ARK Space Exploration ETF',TQQQ:'ProShares UltraPro QQQ',
  SQQQ:'ProShares UltraPro Short QQQ',SPXL:'Direxion Daily S&P 500 Bull 3x',
  SOXL:'Direxion Daily Semiconductors Bull 3x',SOXS:'Direxion Daily Semiconductors Bear 3x',
  SCHD:'Schwab US Dividend Equity ETF',JEPI:'JPMorgan Equity Premium Income ETF',
  JEPQ:'JPMorgan Nasdaq Equity Premium Income ETF',DIVO:'Amplify CWP Enhanced Dividend Income ETF',
  HDV:'iShares Core High Dividend ETF',VYM:'Vanguard High Dividend Yield ETF',
  DVY:'iShares Select Dividend ETF',SPYD:'SPDR Portfolio S&P 500 High Dividend ETF',
  VNQ:'Vanguard Real Estate ETF',SCHH:'Schwab US REIT ETF',IYR:'iShares US Real Estate ETF',
  IBIT:'iShares Bitcoin Trust',FBTC:'Fidelity Wise Origin Bitcoin Fund',
  RSP:'Invesco S&P 500 Equal Weight ETF',IJR:'iShares Core S&P Small-Cap ETF',
  MDY:'SPDR S&P MidCap 400 ETF',
  FTEC:'Fidelity MSCI Information Technology ETF',FDN:'First Trust Dow Jones Internet Index ETF',
  SKYY:'First Trust Cloud Computing ETF',CLOU:'Global X Cloud Computing ETF',
  IGV:'iShares Expanded Tech-Software ETF',
  IBB:'iShares Biotechnology ETF',XBI:'SPDR S&P Biotech ETF',
  IYT:'iShares Transportation Average ETF',JETS:'US Global Jets ETF',
  GDX:'VanEck Gold Miners ETF',GDXJ:'VanEck Junior Gold Miners ETF',
  TAN:'Invesco Solar ETF',ICLN:'iShares Global Clean Energy ETF',
  QCLN:'First Trust NASDAQ Clean Edge Green Energy ETF',
  SGOV:'iShares 0-3 Month Treasury Bond ETF',BIL:'SPDR Bloomberg 1-3 Month T-Bill ETF',
  TIP:'iShares TIPS Bond ETF',VTIP:'Vanguard Short-Term Inflation-Protected Securities ETF',
  VMBS:'Vanguard Mortgage-Backed Securities ETF',MBB:'iShares MBS ETF',
  PFF:'iShares Preferred and Income Securities ETF',
  EWJ:'iShares MSCI Japan ETF',EWZ:'iShares MSCI Brazil ETF',
  EWC:'iShares MSCI Canada ETF',EWA:'iShares MSCI Australia ETF',
  EWG:'iShares MSCI Germany ETF',EWU:'iShares MSCI United Kingdom ETF',
  FXI:'iShares China Large-Cap ETF',KWEB:'KraneShares CSI China Internet ETF',
  MCHI:'iShares MSCI China ETF',IEMG:'iShares Core MSCI Emerging Markets ETF',
  VXUS:'Vanguard Total International Stock ETF',ACWI:'iShares MSCI ACWI ETF',
  BITO:'ProShares Bitcoin Strategy ETF',ETHE:'Grayscale Ethereum Trust',
  GBTC:'Grayscale Bitcoin Trust',
  UPRO:'ProShares UltraPro S&P500',SPXS:'Direxion Daily S&P 500 Bear 3x',
  LABU:'Direxion Daily S&P Biotech Bull 3x',LABD:'Direxion Daily S&P Biotech Bear 3x',
  MOO:'VanEck Agribusiness ETF',XME:'SPDR S&P Metals and Mining ETF',
  SIL:'Global X Silver Miners ETF',
}

// De-duplicate while preserving order
function dedup(arr: string[]): string[] {
  return [...new Set(arr)]
}

export const UNIVERSE_FLAT = Object.entries(STOCK_UNIVERSE).flatMap(([sector, symbols]) =>
  dedup(symbols).map(sym => ({ symbol: sym, name: STOCK_NAMES[sym] ?? sym, sector }))
)

export const SECTORS = Object.keys(STOCK_UNIVERSE)

export const ALL_SYMBOLS = dedup(Object.values(STOCK_UNIVERSE).flat())

// Curated set of high-search-demand tickers. Only these stock pages are
// indexed + listed in the sitemap; the rest are noindex,follow to avoid a
// "thin/scaled content" footprint (AdSense / Search quality). The pages still
// render for any ticker — they're just not pushed for indexing.
export const TOP_STOCKS: string[] = dedup([
  // Mega/large-cap tech & internet
  'AAPL','MSFT','GOOGL','GOOG','AMZN','NVDA','META','TSLA','AVGO','ORCL',
  'ADBE','CRM','AMD','INTC','QCOM','CSCO','IBM','TXN','NOW','INTU',
  'PLTR','MU','AMAT','LRCX','KLAC','ARM','SMCI','DELL','PANW','CRWD',
  'SNOW','NET','DDOG','ZS','MDB','UBER','ABNB','SHOP','PYPL','COIN',
  'HOOD','SOFI','RBLX','SNAP','SPOT','NFLX','BABA','NIO',
  // Financials
  'JPM','BAC','WFC','C','GS','MS','BLK','SCHW','AXP','V',
  'MA','BRK-B','COF','USB','PNC',
  // Healthcare
  'UNH','JNJ','LLY','PFE','MRK','ABBV','TMO','ABT','DHR','BMY',
  'AMGN','GILD','CVS','MRNA',
  // Consumer & retail
  'WMT','COST','HD','LOW','NKE','MCD','SBUX','TGT','KO','PEP',
  'PG','PM','MO','DIS','CMCSA','TJX','BKNG','CMG',
  // Energy, industrial, autos
  'XOM','CVX','COP','SLB','OXY','BA','CAT','GE','HON','UPS',
  'FDX','LMT','RTX','DE','MMM','F','GM','T','VZ','TMUS',
  // Popular ETFs
  'SPY','QQQ','VOO','VTI','IWM','DIA','GLD','SLV','TLT','ARKK',
  'XLF','XLE','XLK','SCHD','JEPI','VYM','VIG',
  // Meme / retail favorites
  'GME','AMC',
])

const TOP_STOCKS_SET = new Set(TOP_STOCKS)
export const isTopStock = (symbol: string) => TOP_STOCKS_SET.has(symbol.toUpperCase())

// Whole curated universe (organized by sector, real companies). Used to safely
// expand indexing beyond TOP_STOCKS: a universe ticker is indexed only when its
// page actually has real data (see generateMetadata + hasSeoData), so obscure
// tickers with no data stay noindex and never become "scaled content".
const UNIVERSE_SET = new Set(ALL_SYMBOLS.map((s) => s.toUpperCase()))
export const isInUniverse = (symbol: string) => UNIVERSE_SET.has(symbol.toUpperCase())

// Exchange-traded funds within our universe — marked as InvestmentFund (not
// Corporation) in structured data, since the schema type must match the asset.
export const ETF_SYMBOLS = new Set([
  'SPY', 'QQQ', 'VOO', 'VTI', 'IWM', 'DIA', 'GLD', 'SLV', 'TLT', 'ARKK',
  'XLF', 'XLE', 'XLK', 'SCHD', 'JEPI', 'VYM', 'VIG',
])
export const isEtf = (symbol: string) => ETF_SYMBOLS.has(symbol.toUpperCase())

export function getSector(symbol: string): string | null {
  for (const [sector, syms] of Object.entries(STOCK_UNIVERSE)) {
    if (syms.includes(symbol)) return sector
  }
  return null
}
